# Generated by Django 6.1.1 on 2026-09-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_slug', models.SlugField()),
                ('document_title', models.CharField(max_length=255)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_slug', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document_slug', 'chunk_index'), name='unique_chunk_per_document')],
            },
        ),
    ]
